apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-deployment
  namespace: demo
spec:
  selector:
    matchLabels:
      app: guestbook
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
        - name: guestbook-controller
          image: errorbyte/guestbook-controller